config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'cals/index'
  get 'navis/index'
  get 'home/index'
  root 'home#index'
  resources :cals
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cal.rb
class Cal < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cals_controller.rb
class CalsController < ApplicationController
  before_action :move_to_index, except: [:root, :show]

  def index
    @cals = Cal.all
  end

  def new
    @cal = Cal.new
  end

  def show
    @cal = Cal.find(params[:id])
  end

  def create
    Cal.create(cal_parameter)
    redirect_to cals_path
  end

  def destroy
    @cal = Cal.find(params[:id])
    @cal.destroy
    redirect_to cals_path, notice:"削除しました"
  end

  def edit
    @cal = Cal.find(params[:id])
  end

  def update
    @cal = Cal.find(params[:id])
    if @cal.update(cal_parameter)
      redirect_to cals_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  def move_to_index
    unless user_signed_in?
      redirect_to :root
    end
  end

  private

  def cal_parameter
    params.require(:cal).permit(:title, :content, :start_time)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/navis_controller.rb
class NavisController < ApplicationController
  def index
  end

  def create
    Cal.create(cal_parameter)
    redirect_to cals_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cals_helper.rb
module CalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/navis_helper.rb
module NavisHelper
end

app/views/cals/_header.html.haml
.navbar.navbar-expand-md.navbar-dark.bg-dark.mb-4{:role => "navigation"}
  %a.navbar-brand{:href => "/home/index"} ドコイク？
  %button.navbar-toggler{"aria-controls" => "navbarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarCollapse.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item
        %a.nav-link{:href => "/home/index"} Home
      %li.nav-item.active
      - if user_signed_in?
        %a.nav-link{:href => "/cals/index"} マイページ
      %li.nav-item
        %a.nav-link{:href => "/navis/index"} ドコイクナビ
    - if user_signed_in?
      .user_nav.grid-6
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "post"
    - else
      .grid-6
        = link_to "ログイン", new_user_session_path, class: "post"
        = link_to "新規登録", new_user_registration_path, class: "post"
    -# %form.form-inline.mt-2.mt-md-0
    -#   %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "text"}/
    -#   %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search

app/views/cals/edit.html.haml
.wrapper
  = render "header"

= form_with(model: @cal, local: true) do |form|
  .title
    = form.label :目的地
    = form.text_field :title
  .time
    = form.label :開始時間
    = form.datetime_select :start_time
  .content
    = form.label :メモ
    = form.text_field :content
  .submit
    = form.submit

app/views/cals/index.html.haml
.wrapper
  = render "header"

%p#notice= notice
%h1
  #{current_user.email}
%table
  %thead
    %tr
      %th 目的地
      %th 時間
      %th{:colspan => "3"}
  %tbody
    - @cals.each do |cal|
      %tr
        %td= cal.title
        %td= cal.start_time.strftime("%Y-%m-%d %H:%M")
        %td= link_to '詳細', cal
        %td= link_to '編集', edit_cal_path(cal.id)
        %td= link_to '削除',cal_path(cal.id), method: :delete, data: { confirm: '本当に削除してよろしいですか？' }
%br/
= link_to '予定を立てる', new_cal_path
= month_calendar events: @cals do |date, cals|
  = date.day
  - cals.each do |cal|
    %div
      = link_to cal.title, cal

app/views/cals/new.html.haml
.wrapper
  = render "header"

= form_with(model: @cal, local: true) do |form|
  .title
    = form.label :目的地
    = form.text_field :title
  .time
    = form.label :開始時間
    = form.datetime_select :start_time
  .content
    = form.label :メモ
    = form.text_field :content
  .submit
    = form.submit

app/views/cals/show.html.haml
.wrapper
  = render "header"

%p#notice= notice
%p
  %strong 目的地
  = @cal.title
%p
  %strong 開始時間
  = @cal.start_time.strftime("%Y-%m-%d %H:%M")
%p
  %strong メモ
  = @cal.content
= link_to '編集', edit_cal_path(@cal)
|
= link_to '戻る', cals_path

app/views/home/_header.html.haml
.navbar.navbar-expand-md.navbar-dark.bg-dark.mb-4{:role => "navigation"}
  %a.navbar-brand{:href => "/home/index"} ドコイク？
  %button.navbar-toggler{"aria-controls" => "navbarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarCollapse.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %a.nav-link{:href => "/home/index"} Home
      %li.nav-item
      - if user_signed_in?
        %a.nav-link{:href => "/cals/index"} マイページ
      %li.nav-item
        %a.nav-link{:href => "/navis/index"} ドコイクナビ
    - if user_signed_in?
      .user_nav.grid-6
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "post"
    - else
      .grid-6
        = link_to "ログイン", new_user_session_path, class: "post"
        = link_to "新規登録", new_user_registration_path, class: "post"
    -# %form.form-inline.mt-2.mt-md-0
    -#   %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "text"}/
    -#   %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search

app/views/home/index.html.haml
.wrapper
  = render "header"
  
%p#notice= notice
.container
  .row
    .col-md-6.jasgrid
      .box-item
        .box-post
          %span.label.label-success
            %a{:href => "https://www.walkerplus.com/article_list/ar0600/", :rel => "tag"} 東海ウォーカー
          %h1.post-title
            %a{:href => "https://www.walkerplus.com/article/1004000/"}
              この夏食べたい！愛知の最新おすすめパフェ5選
          %span.meta
            %span
              %i.glyphicon.glyphicon-comment
              %a{:href => "http://wordpress.thebebel.com/showcase/newsbook/2015/01/19/meet-asias-best-destinations-for-the-summer/#respond"} No Comments
            %span
              %i.glyphicon.glyphicon-time
              Jul 16, 2020
        %img{:alt => "この夏食べたい！愛知の最新おすすめパフェ5選", :src => "https://news.walkerplus.com/article/1004000/10027977_615.jpg"}/
      .box-item
        .box-post
          %span.label.label-success
            %a{:href => "#", :rel => "tag"} 東京ディズニーリゾート・ブログ
          %h1.post-title
            %a{:href => "https://www.tokyodisneyresort.jp/tdrblog/detail/200415/"}
              東京ディズニーリゾートは今日で37周年！
          %span.meta
            %span
              %i.glyphicon.glyphicon-comment
              %a{:href => "http://wordpress.thebebel.com/showcase/newsbook/2015/01/19/meet-asias-best-destinations-for-the-summer/#respond"} No Comments
            %span
              %i.glyphicon.glyphicon-time
              Apr 15, 2020
        %img{:alt => "東京ディズニーリゾートは今日で37周年！", :src => "https://media1.tokyodisneyresort.jp/images/adventure/blog/img200415_1.jpg"}/
      .box-item
        .box-post
          %span.label.label-success
            %a{:href => "https://retty.news/", :rel => "tag"} Retty
          %h1.post-title
            %a{:href => "https://retty.news/35884/"}
              "おいしい"のコツは「蒸らす」こと！脱サラして始めたこだわりのとんかつ屋「成満堂」
          %span.meta
            %span
              %i.glyphicon.glyphicon-comment
              %a{:href => "http://wordpress.thebebel.com/showcase/newsbook/2015/01/19/meet-asias-best-destinations-for-the-summer/#respond"} No Comments
            %span
              %i.glyphicon.glyphicon-time
              Aug 1, 2019
        %img{:alt => "おいしいのコツは「蒸らす」こと！脱サラして始めたこだわりのとんかつ屋「成満堂」", :src => "https://ximg.retty.me/resize/s1328x1328/-/retty_news/articles/20190724054741-49mxc.jpg"}/
      -# .box-item
      -#   .box-post
      -#     %span.label.label-success
      -#       %a{:href => "#", :rel => "tag"} Travel
      -#     %h1.post-title
      -#       %a{:href => "#"}
      -#         The ‘sky pool’ is just the start: London prepares for a flood of bathing oligarchs
      -#     %span.meta
      -#       %span
      -#         %i.glyphicon.glyphicon-comment
      -#         %a{:href => "http://wordpress.thebebel.com/showcase/newsbook/2015/01/19/meet-asias-best-destinations-for-the-summer/#respond"} No Comments
      -#       %span
      -#         %i.glyphicon.glyphicon-time
      -#         Sep 15, 2015
      -#   %img{:alt => "The ‘sky pool’ is just the start: London prepares for a flood of bathing oligarchs", :src => "https://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2015/8/20/1440084421494/658509dc-71ec-4329-a44a-65a8968f31eb-2060x1236.jpeg?w=700&q=85&auto=format&sharp=10&s=95d11c21789512a206c58f6e09161c3b"}/
      -# .box-item
      -#   .box-post
      -#     %span.label.label-success
      -#       %a{:href => "#", :rel => "tag"} Travel
      -#     %h1.post-title
      -#       %a{:href => "#"}
      -#         Carbuncle Cup: Walkie Talkie wins prize for worst building of the year
      -#     %span.meta
      -#       %span
      -#         %i.glyphicon.glyphicon-comment
      -#         %a{:href => "http://wordpress.thebebel.com/showcase/newsbook/2015/01/19/meet-asias-best-destinations-for-the-summer/#respond"} No Comments
      -#       %span
      -#         %i.glyphicon.glyphicon-time
      -#         Sep 15, 2015
      -#   %img{:alt => "Carbuncle Cup: Walkie Talkie wins prize for worst building of the year", :src => "https://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2015/9/1/1441111760813/babad85b-8749-43dd-8b0a-dda57f7de279-2060x1236.jpeg?w=700&q=85&auto=format&sharp=10&s=943b47a6776b1ecbfb4c6db7d8932d45"}/
    .col-md-6.jasgrid
      .box-item
        .box-post
          %span.label.label-success
            %a{:href => "https://www.nagashima-onsen.co.jp/nabana/index.html", :rel => "tag"} なばなの里
          %h1.post-title
            %a{:href => "https://www.nagashima-onsen.co.jp/nabana/info/SUMMERILLUMINATION.html"}
              初開催：なばなの里 “サマーイルミネーション” 夜を彩る「天の川」
          %span.meta
            %span
              %i.glyphicon.glyphicon-comment
              %a{:href => "http://wordpress.thebebel.com/showcase/newsbook/2015/01/19/meet-asias-best-destinations-for-the-summer/#respond"} No Comments
            %span
              %i.glyphicon.glyphicon-time
              Aug 6, 2020
        %img{:alt => "'初開催：なばなの里 “サマーイルミネーション” 夜を彩る「天の川」", :src => "https://www.nagashima-onsen.co.jp/nabana/wp-content/uploads/sites/6/2020/07/2512bc8e05a9cf1781f534473dc3d4d3.jpg"}/
      .box-item
        .box-post
          %span.label.label-success
            %a{:href => "https://www.jalan.net/news/", :rel => "tag"} じゃらんニュース
          %h1.post-title
            %a{:href => "https://www.jalan.net/news/article/422327/"}
              マリオになれる？USJ「任天堂」エリアの詳細を発表！スマホと連動、新時代のテーマパーク体験！
          %span.meta
            %span
              %i.glyphicon.glyphicon-comment
              %a{:href => "http://wordpress.thebebel.com/showcase/newsbook/2015/01/19/meet-asias-best-destinations-for-the-summer/#respond"} No Comments
            %span
              %i.glyphicon.glyphicon-time
              Jan 17, 2020
        %img{:alt => "マリオになれる？USJ「任天堂」エリアの詳細を発表！スマホと連動、新時代のテーマパーク体験！", :src => "https://www.fashion-press.net/img/news/27499/9dw.jpg"}/
      .box-item
        .box-post
          %span.label.label-success
            %a{:href => "https://tripnote.jp/", :rel => "tag"} トリップノート
          %h1.post-title
            %a{:href => "https://tripnote.jp/article/first-trip-osusume"}
              初めての海外旅行におすすめ！海外初心者に人気の国・都市11選
          %span.meta
            %span
              %i.glyphicon.glyphicon-comment
              %a{:href => "http://wordpress.thebebel.com/showcase/newsbook/2015/01/19/meet-asias-best-destinations-for-the-summer/#respond"} No Comments
            %span
              %i.glyphicon.glyphicon-time
              May 13, 2019
        %img{:alt => "初めての海外旅行におすすめ！海外初心者に人気の国・都市11選", :src => "https://tripnote.imgix.net/post/article/1414/141311-5XEpZ0suQXqzJaWHt72M_lrg.jpg?w=768&h=474&fit=crop"}/
      -# .box-item
      -#   .box-post
      -#     %span.label.label-success
      -#       %a{:href => "#", :rel => "tag"} Travel
      -#     %h1.post-title
      -#       %a{:href => "#"}
      -#         Sailing off Iceland … is no holiday
      -#     %span.meta
      -#       %span
      -#         %i.glyphicon.glyphicon-comment
      -#         %a{:href => "http://wordpress.thebebel.com/showcase/newsbook/2015/01/19/meet-asias-best-destinations-for-the-summer/#respond"} No Comments
      -#       %span
      -#         %i.glyphicon.glyphicon-time
      -#         Sep 15, 2015
      -#   %img{:alt => "Sailing off Iceland is no holiday", :src => "https://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2015/9/10/1441897683067/cbd64c76-4d4b-4fdc-b21e-09ee8c61fe84-2060x1371.jpeg?w=620&q=85&auto=format&sharp=10&s=902f73c53527356ce69674be7218a12b"}/
      -# .box-item
      -#   .box-post
      -#     %span.label.label-success
      -#       %a{:href => "#", :rel => "tag"} Travel
      -#     %h1.post-title
      -#       %a{:href => "#"}
      -#         Online Gothenburg: tech travel tips
      -#     %span.meta
      -#       %span
      -#         %i.glyphicon.glyphicon-comment
      -#         %a{:href => "http://wordpress.thebebel.com/showcase/newsbook/2015/01/19/meet-asias-best-destinations-for-the-summer/#respond"} No Comments
      -#       %span
      -#         %i.glyphicon.glyphicon-time
      -#         Sep 15, 2015
      -#   %img{:alt => "Online Gothenburg: tech travel tips", :src => "https://i.guim.co.uk/img/media/45532d8551c9033d4bc18abf7adfc5ee29405fff/0_928_3220_1932/master/3220.jpg?w=700&q=85&auto=format&sharp=10&s=776a7ea32d0c2df42d8470d4cc210bfe"}/
      -# .box-item
      -#   .box-post
      -#     %span.label.label-success
      -#       %a{:href => "#", :rel => "tag"} Travel
      -#     %h1.post-title
      -#       %a{:href => "#"}
      -#         Online Gothenburg: tech travel tips
      -#     %span.meta
      -#       %span
      -#         %i.glyphicon.glyphicon-comment
      -#         %a{:href => "http://wordpress.thebebel.com/showcase/newsbook/2015/01/19/meet-asias-best-destinations-for-the-summer/#respond"} No Comments
      -#       %span
      -#         %i.glyphicon.glyphicon-time
      -#         Sep 15, 2015
      -#   %img{:alt => "Explore Lyon: essential travel apps and tips", :src => "https://i.guim.co.uk/img/media/5563b9b5cd87bab2e9c9279a8f0c7268b69471bc/0_172_5616_3368/master/5616.jpg?w=700&q=85&auto=format&sharp=10&s=7a9664aabfe4b691120166f61759ba68"}/

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Dokoiku
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/layouts/hoge.html.haml
- if user_signed_in?
  .user_nav.grid-6
    = link_to "ログアウト", destroy_user_session_path, method: :delete
    = link_to "投稿する", new_tweet_path, class: "post"
- else
  .grid-6
    = link_to "ログイン", new_user_session_path, class: "post"
    = link_to "新規登録", new_user_registration_path, class: "post"

app/views/navis/_header.html.haml
.navbar.navbar-expand-md.navbar-dark.bg-dark.mb-4{:role => "navigation"}
  %a.navbar-brand{:href => "/home/index"} ドコイク？
  %button.navbar-toggler{"aria-controls" => "navbarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarCollapse.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item
        %a.nav-link{:href => "/home/index"} Home
      %li.nav-item
      - if user_signed_in?
        %a.nav-link{:href => "/cals/index"} マイページ
      %li.nav-item.active
        %a.nav-link{:href => "/navis/index"} ドコイクナビ
    - if user_signed_in?
      .user_nav.grid-6
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "post"
    - else
      .grid-6
        = link_to "ログイン", new_user_session_path, class: "post"
        = link_to "新規登録", new_user_registration_path, class: "post"
    -# %form.form-inline.mt-2.mt-md-0
    -#   %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "text"}/
    -#   %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search

app/views/navis/index.html.haml
.wrapper
  = render "header"

.balloon5
  .faceicon
    %img{:alt => "navigator", :src => "https://3.bp.blogspot.com/-zYuktPv0JNI/Wp94GJY-9EI/AAAAAAABKqs/ZebVBqj3y2k5-dELWHhZbtQAbYvmbG8DACLcBGAs/s400/kid_job_boy_teacher.png"}/
  .chatting
    .says
      %p あなたの予定をナビします！
.quiz_area
  .quiz_set
    -# %p.quiz_no
    .quiz_question
    .quiz_ans_area
      %ul
    .quiz_area_bg
    .quiz_area_icon
  .quiz_result

app/views/simple_calendar/_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    %span.calendar-title
      = t('date.month_names')[start_date.month]
      = start_date.year
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        = content_tag :tr, class: calendar.tr_classes_for(week) do
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block)
                - capture_haml(day, sorted_events.fetch(day, []), &passed_block)
              - else
                - passed_block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_month_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: '前の月'), calendar.url_for_previous_view
    %span.calendar-title
      = t('date.month_names')[start_date.month]
      = start_date.year
    = link_to t('simple_calendar.next', default: '次の月'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block)
                - capture_haml(day, sorted_events.fetch(day, []), &passed_block)
              - else
                - passed_block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_week_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    - if calendar.number_of_weeks == 1
      %span.calendar-title
        Week #{calendar.week_number}
    - else
      %span.calendar-title
        Week #{calendar.week_number} - #{calendar.end_week}
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block)
                - capture_haml(day, sorted_events.fetch(day, []), &passed_block)
              - else
                - passed_block.call day, sorted_events.fetch(day, [])